all: c_create_d_delete.exe
c_create_d_delete.o: c_create_d_delete.c
	gcc -c c_create_d_delete.c
c_create_d_delete.exe: c_create_d_delete.o
	gcc -o c_create_d_delete.exe c_create_d_delete.o
clean:
	rm c_create_d_delete.o c_create_d_delete.exe